stages:
  - build
  - test

build executable:
  image: rust:1.35.0
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/crust

run tests:
  image: gcc:9.1.0
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - cd tests/
  script:
    - ./test_compiler.sh ../target/release/crust 1
