stages:
  - build
  - test

build executable:
  image: rust:1.35.0
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/crust

run tests:
  image: bash:5.0.7
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - tests/test_compiler.sh target/release/crust
